/**
 * One-time script to seed mock leads into Firestore.
 * Run with: node scripts/seed.mjs
 *
 * Safe to re-run — uses setDoc with specific IDs, so existing docs are overwritten
 * (requires the realtor to be the one running it, or allow create: if true rule handles first run)
 */

import { initializeApp } from 'firebase/app'
import { getFirestore, doc, setDoc, Timestamp } from 'firebase/firestore'

const firebaseConfig = {
  apiKey: 'AIzaSyAvlDM_JhC-Q2iGYSNPTmYKU9NoBNwtowI',
  authDomain: 'ignite-33d2d.firebaseapp.com',
  projectId: 'ignite-33d2d',
  storageBucket: 'ignite-33d2d.firebasestorage.app',
  messagingSenderId: '954708739917',
  appId: '1:954708739917:web:34f4b87e3c5d1d58db1904',
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

// ── Inline mock data (matches src/data/mockData.js) ──────────────────────────
// Using a subset of fields; the normalizer fills in everything else.
// Each lead doc keeps the full rich structure so the CRM renders perfectly.

const leads = [
  { id: 1, name: 'Marcus Thompson', initials: 'MT', phone: '(813) 555-0192', email: 'marcus.t@gmail.com', source: 'Zillow', temperature: 'hot', intentScore: 94, lastActive: '23 min ago', lastActiveMs: 23 * 60 * 1000, tags: ['High-Intent Financial Buyer', 'School District Focus'], summary: 'Viewed all 40 photos on 142 Maplewood Dr. Used the mortgage calculator 3x in 48 hrs. Spent 12 minutes on the tax history page.', properties: ['142 Maplewood Dr', '88 Northview Ct'], scoreBreakdown: { depth: 95, recency: 98, financial: 90 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '23 min ago', event: 'Viewed all 40 listing photos on 142 Maplewood Dr', type: 'photos', highlight: true }, { id: 2, time: '1 hr ago', event: 'Used mortgage calculator — estimated $420K budget', type: 'financial', highlight: true }, { id: 3, time: '3 hrs ago', event: 'Spent 12 min on tax history page for 142 Maplewood Dr', type: 'financial', highlight: true }, { id: 4, time: 'Yesterday 9:14 PM', event: 'Saved 88 Northview Ct to favorites', type: 'save', highlight: false }, { id: 5, time: '2 days ago', event: 'Submitted inquiry form via Zillow', type: 'inquiry', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Marcus! I noticed you've been spending some serious time on 142 Maplewood — especially the financials. I think you found something special there. I have an update on recent comps in that neighborhood that could shape your offer. Want me to send it over?" }, { channel: 'Email', subject: 'Quick update on 142 Maplewood Dr', message: "Hi Marcus,\n\nI saw you've been digging into 142 Maplewood Dr — especially the tax history and calculator tools. That tells me you're thinking seriously about this one.\n\nI pulled some updated comparable sales in that area that could directly affect your offer strategy. Would love to connect for a quick 10-minute call this week.\n\nLooking forward to talking soon,\n[Your Name]" }] },
  { id: 2, name: 'Sarah Chen', initials: 'SC', phone: '(727) 555-0348', email: 'schen.home@gmail.com', source: 'Website', temperature: 'hot', intentScore: 88, lastActive: '1 hr ago', lastActiveMs: 60 * 60 * 1000, tags: ['Late-Night Searcher', 'Price Drop Alert Subscriber'], summary: 'Active at 11 PM and 12:30 AM on weeknights. Subscribed to price-drop alerts on 3 properties. Viewed floor plans on 6 different listings.', properties: ['310 Clearwater Blvd', '74 Sunset Ridge Ln', '201 Harbor View Dr'], scoreBreakdown: { depth: 88, recency: 95, financial: 80 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '1 hr ago', event: 'Browsed 310 Clearwater Blvd at 11:47 PM', type: 'revisit', highlight: true }, { id: 2, time: 'Last night 12:31 AM', event: 'Viewed floor plan details on 74 Sunset Ridge Ln', type: 'photos', highlight: false }, { id: 3, time: '2 days ago', event: 'Subscribed to price-drop alert on 3 properties', type: 'financial', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey Sarah! You've been on my radar — you're clearly doing your homework on Clearwater Blvd late at night! I just heard that the seller on 310 is open to offers before it hits a price drop. Want to get ahead of it?" }, { channel: 'Email', subject: 'Before the price drops on 310 Clearwater Blvd', message: "Hi Sarah,\n\nI noticed you set a price-drop alert on 310 Clearwater Blvd — good instinct. I actually have some intel from the listing agent that the seller is motivated and reviewing offers this week, before any public price reduction.\n\nThis could be your chance to get it at today's price with less competition. Want to schedule a showing?\n\nBest,\n[Your Name]" }] },
  { id: 3, name: 'Natalie Brooks', initials: 'NB', phone: '(813) 555-0577', email: 'nbrooks.re@icloud.com', source: 'Referral', temperature: 'hot', intentScore: 85, lastActive: '2 hrs ago', lastActiveMs: 2 * 60 * 60 * 1000, tags: ['Motivated by Timeline', 'Pre-Approval Engaged'], summary: "Referred by past client Dana Mills. Clicked the pre-approval tool twice. Mentions needing to close before August in her inquiry notes.", properties: ['509 Magnolia Ave', '18 Coral Gate Dr'], scoreBreakdown: { depth: 82, recency: 85, financial: 92 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '2 hrs ago', event: 'Returned to pre-approval tool for the 2nd time', type: 'financial', highlight: true }, { id: 2, time: '5 hrs ago', event: 'Viewed 509 Magnolia Ave for 18 minutes', type: 'photos', highlight: false }, { id: 3, time: '2 days ago', event: "Submitted inquiry — notes mention 'must close by August'", type: 'inquiry', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey Natalie! Dana had great things to say about you. I saw you're getting your pre-approval ducks in a row — smart move. With your August timeline, I want to make sure we have the right options lined up. Can we jump on a quick call this week?" }, { channel: 'Email', subject: 'Your August timeline — let\'s map it out', message: "Hi Natalie,\n\nSo great to connect — Dana is wonderful and I'm excited to help you find your next home.\n\nI noticed your inquiry mentioned an August close deadline. That actually gives us a solid runway if we move with intention.\n\nCan we schedule a 20-minute discovery call this week?\n\nBest,\n[Your Name]" }] },
  { id: 4, name: 'David Rodriguez', initials: 'DR', phone: '(352) 555-0814', email: 'd.rodriguez.home@gmail.com', source: 'Zillow', temperature: 'hot', intentScore: 82, lastActive: '4 hrs ago', lastActiveMs: 4 * 60 * 60 * 1000, tags: ['Comparative Shopper', 'Neighborhood Focused'], summary: 'Compared 4 properties side-by-side in the same zip code. Repeatedly filters by school district. Has viewed the same listing 5 separate times.', properties: ['92 Pinehurst Blvd', '45 Ridgewood Way', '7 Elmwood Ct'], scoreBreakdown: { depth: 90, recency: 75, financial: 78 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '4 hrs ago', event: 'Returned to 92 Pinehurst Blvd for the 5th time', type: 'revisit', highlight: true }, { id: 2, time: 'Yesterday', event: 'Compared 4 listings side-by-side in the 34209 zip code', type: 'search', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey David! You've been doing your homework on 92 Pinehurst — I can see why, it's a strong listing for that school district. I actually just heard about a new home hitting the Northview zone on Friday that isn't on Zillow yet. Want the details first?" }, { channel: 'Email', subject: 'A new Northview listing — before it\'s public', message: "Hi David,\n\nI noticed you've been closely comparing homes in the Northview school zone — you clearly know what you want.\n\nI just received word about a new listing in that exact area that will be hitting the MLS on Friday. I'd love to get you a private preview.\n\nInterested?\n\nBest,\n[Your Name]" }] },
  { id: 5, name: 'Kevin Zhang', initials: 'KZ', phone: '(813) 555-0261', email: 'kevinz.homes@gmail.com', source: 'Zillow', temperature: 'warm', intentScore: 79, lastActive: '6 hrs ago', lastActiveMs: 6 * 60 * 60 * 1000, tags: ['Strong Financial Signals', 'Investment Mindset'], summary: 'Opened the ROI calculator on two separate investment properties. Viewed rental income projections. Engaged with open house schedule.', properties: ['881 Bayside Dr Unit 4B', '1205 Gulf View Terr'], scoreBreakdown: { depth: 80, recency: 72, financial: 88 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '6 hrs ago', event: 'Used ROI calculator on 881 Bayside Dr Unit 4B', type: 'financial', highlight: true }, { id: 2, time: 'Yesterday', event: 'Viewed rental income projection page for 10 min', type: 'financial', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey Kevin! I saw you ran the numbers on Bayside Dr — solid cap rate on that one. I have some updated rental income data for that building that might tip the scales for you. Want me to shoot it over?" }, { channel: 'Email', subject: 'Updated rental data for 881 Bayside Dr', message: "Hi Kevin,\n\nI could see you've been analyzing the investment potential on 881 Bayside — great eye. I just pulled the actual rental income history for that unit.\n\nWould it help to review those numbers together on a quick call?\n\nBest,\n[Your Name]" }] },
  { id: 6, name: 'Jennifer Walsh', initials: 'JW', phone: '(727) 555-0493', email: 'jen.walsh.home@yahoo.com', source: 'Facebook', temperature: 'warm', intentScore: 76, lastActive: '8 hrs ago', lastActiveMs: 8 * 60 * 60 * 1000, tags: ['School District Focus', 'Consistent Browser'], summary: 'Visits the site almost daily but has not used any financial tools yet. Has saved 7 properties, all in the same school district corridor.', properties: ['33 Willowbrook Ave', '119 Cedar Ridge Rd', '604 Timberline Dr'], scoreBreakdown: { depth: 78, recency: 82, financial: 45 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '8 hrs ago', event: 'Saved 33 Willowbrook Ave to favorites (7th saved property)', type: 'save', highlight: true }, { id: 2, time: 'Yesterday', event: 'Browsed school district ratings page for 8 minutes', type: 'search', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey Jennifer! I've noticed you've been saving a lot of homes along the Willowbrook/Cedar Ridge corridor — you clearly know what area you want. I just saw a listing come through in that exact zone that isn't live yet. Want me to send you the details?" }, { channel: 'Email', subject: '7 saves and counting — let me help you narrow it down', message: "Hi Jennifer,\n\nYou've been doing a lot of great research and the school district is clearly a top priority. You've saved some really strong options.\n\nSometimes a 15-minute conversation can cut through the noise. Would you be open to a quick call?\n\nBest,\n[Your Name]" }] },
  { id: 7, name: 'Mike Okonkwo', initials: 'MO', phone: '(813) 555-0729', email: 'mike.okonkwo@gmail.com', source: 'Zillow', temperature: 'warm', intentScore: 71, lastActive: '12 hrs ago', lastActiveMs: 12 * 60 * 60 * 1000, tags: ['Steady Engagement', 'Needs Nudge'], summary: 'Consistent 3-4 visits per week for 3 weeks. Has not filled out a contact form but views new listings quickly when they hit.', properties: ['217 Lakeview Dr', '58 Palmetto Way'], scoreBreakdown: { depth: 70, recency: 78, financial: 62 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '12 hrs ago', event: 'Viewed 217 Lakeview Dr within 2 hrs of it being listed', type: 'revisit', highlight: true }, { id: 2, time: 'Yesterday', event: 'Viewed 58 Palmetto Way — 22 photos, virtual tour', type: 'photos', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Mike! You've been quietly browsing for a few weeks and you were one of the first people to check out 217 Lakeview when it went live. That kind of quick reaction usually means you know your market. I'd love to help you pull the trigger — want to connect?" }, { channel: 'Email', subject: 'You found 217 Lakeview before anyone else did', message: "Hi Mike,\n\nI noticed you viewed 217 Lakeview Dr within 2 hours of it hitting the market. I work with a few buyers in the Palmetto Way area and often hear about new inventory before it's listed.\n\nIf you want a first-look advantage, a quick conversation could be really valuable.\n\nBest,\n[Your Name]" }] },
  { id: 8, name: 'Ashley Monroe', initials: 'AM', phone: '(727) 555-0164', email: 'ashley.m.realestate@gmail.com', source: 'Instagram', temperature: 'warm', intentScore: 65, lastActive: '1 day ago', lastActiveMs: 24 * 60 * 60 * 1000, tags: ['Social Lead', 'Increasing Activity'], summary: 'Came in through Instagram reel. Activity doubled this week compared to last. Browsed new construction section for the first time yesterday.', properties: ['Harborview New Construction', '405 Pelican Cove Rd'], scoreBreakdown: { depth: 62, recency: 70, financial: 55 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '1 day ago', event: 'Explored new construction section for the first time', type: 'search', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey Ashley! Glad the reel caught your eye — that area really is something special. I noticed you've been checking out new construction lately. I actually toured the Harborview development last week and have some inside info on the best lots. Want the scoop?" }, { channel: 'Email', subject: 'New construction insight — Harborview development', message: "Hi Ashley,\n\nI love that you've been exploring new construction — it's a great option in today's market.\n\nI personally toured the Harborview development last week and can share what I found. New construction moves fast once word gets out.\n\nWant me to put together a quick overview for you?\n\nBest,\n[Your Name]" }] },
  { id: 9, name: 'Robert Kim', initials: 'RK', phone: '(813) 555-0930', email: 'robert.kim.homes@outlook.com', source: 'Website', temperature: 'warm', intentScore: 58, lastActive: '2 days ago', lastActiveMs: 2 * 24 * 60 * 60 * 1000, tags: ['Moderate Engagement', 'Potential'], summary: 'Steady but low-depth engagement. Views listings but rarely goes past photo #10. Has used the contact form once but gave minimal details.', properties: ['722 Osprey Ave', '34 Dolphin Bay Dr'], scoreBreakdown: { depth: 45, recency: 65, financial: 50 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '2 days ago', event: 'Viewed 722 Osprey Ave — 9 photos then left', type: 'photos', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Robert! You've been browsing for a bit and I want to make sure I'm actually helpful. What's the #1 thing you're struggling to find in your search right now? I might be able to point you somewhere useful." }, { channel: 'Email', subject: 'Quick question about your home search', message: "Hi Robert,\n\nI want to be genuinely useful to you, not just send generic listings.\n\nCan I ask — what's the one thing that's been hardest to find so far? Knowing that helps me send you only the things worth your time.\n\nBest,\n[Your Name]" }] },
  { id: 10, name: 'Lisa Park', initials: 'LP', phone: '(727) 555-0452', email: 'lisapark.search@gmail.com', source: 'Zillow', temperature: 'warm', intentScore: 52, lastActive: '2 days ago', lastActiveMs: 2 * 24 * 60 * 60 * 1000, tags: ['Re-engaged Recently', 'Sporadic Pattern'], summary: 'Went quiet for 2 weeks then came back 3 days ago with two sessions in a row. Could indicate a life event that restarted her search.', properties: ['1001 Bayshore Blvd Apt 12C'], scoreBreakdown: { depth: 50, recency: 60, financial: 42 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '2 days ago', event: 'Returned after 2-week gap — viewed 3 listings', type: 'revisit', highlight: true }], smartDrafts: [{ channel: 'Text', message: "Hey Lisa! Welcome back — I noticed you re-started your search this week. Sometimes a break means things have changed. If anything is different for you now — timeline, budget, area — I'd love to help with a fresh perspective." }, { channel: 'Email', subject: "Glad you're back — a few things have changed", message: "Hi Lisa,\n\nI noticed you've been back on the site this week after a brief pause.\n\nWhenever you're ready, I'd love to reconnect. A few things have changed in the market since we last connected.\n\nNo pressure — just here when you need me.\n\nBest,\n[Your Name]" }] },
  { id: 11, name: 'Carlos Mendez', initials: 'CM', phone: '(352) 555-0783', email: 'cmendez.home@gmail.com', source: 'Referral', temperature: 'cold', intentScore: 47, lastActive: '5 days ago', lastActiveMs: 5 * 24 * 60 * 60 * 1000, tags: ['Cooling Fast', 'Was Warm Last Week'], summary: 'Was scoring 71 just 4 days ago. Activity dropped sharply after a burst. May have connected with another agent or found a property elsewhere.', properties: ['230 Magnolia Park Blvd', '77 Harborside Ct'], scoreBreakdown: { depth: 55, recency: 30, financial: 52 }, isAlerted: true, alertType: 'cooling', alertMessage: 'Dropped from 71 → 47 in 4 days. Last active 5 days ago. Risk of losing to competitor.', activity: [{ id: 1, time: '5 days ago', event: 'Last session — viewed 230 Magnolia Park Blvd', type: 'photos', highlight: false }, { id: 2, time: '6 days ago', event: 'Used mortgage calculator for the first time', type: 'financial', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Carlos! I've been thinking about you — it's been a few days and I wanted to check in. Has anything changed in your search? I just came across something near Magnolia Park that I think you'd really like. Want me to send details?" }, { channel: 'Email', subject: 'Checking in — something new in your area', message: "Hi Carlos,\n\nI wanted to reach out personally. I noticed your search activity has been quiet this week, and I just want to make sure I haven't missed a beat for you.\n\nI also just came across a new listing near Magnolia Park that matches what you've been browsing.\n\nStill searching? Let me know.\n\nBest,\n[Your Name]" }] },
  { id: 12, name: 'Brittany Hall', initials: 'BH', phone: '(813) 555-0367', email: 'bhall.real.estate@gmail.com', source: 'Website', temperature: 'cold', intentScore: 41, lastActive: '6 days ago', lastActiveMs: 6 * 24 * 60 * 60 * 1000, tags: ['Ghosting Risk', '6-Day Silence'], summary: 'Had strong back-to-back sessions 6-8 days ago then went completely silent. No trigger event detected. Likely needs a personalized re-engagement.', properties: ['445 Sandpiper Ln', '12 Bay Meadows Cir'], scoreBreakdown: { depth: 48, recency: 22, financial: 44 }, isAlerted: true, alertType: 'ghosting', alertMessage: '6 days of silence after peak engagement. High ghosting risk. Re-engage now.', activity: [{ id: 1, time: '6 days ago', event: 'Last seen — 445 Sandpiper Ln, viewed 31 photos', type: 'photos', highlight: false }, { id: 2, time: '8 days ago', event: 'Peak session — 5 listings, 45 minutes total', type: 'revisit', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Brittany! I know life gets busy, but I was thinking about you. You were really close to something with Sandpiper Ln — I could tell by how much time you spent on it. Did something come up, or has anything changed?" }, { channel: 'Email', subject: "Still in your corner, Brittany", message: "Hi Brittany,\n\nI haven't heard from you in a bit and I just wanted to drop a line — no pressure, no pitch.\n\nYou clearly put a lot of thought into your search, and 445 Sandpiper Ln stood out to you for a reason.\n\nWould a quick 10-minute call this week be useful?\n\nBest,\n[Your Name]" }] },
  { id: 13, name: 'Tom Sullivan', initials: 'TS', phone: '(727) 555-0618', email: 'tomsullivan.search@gmail.com', source: 'Zillow', temperature: 'cold', intentScore: 38, lastActive: '8 days ago', lastActiveMs: 8 * 24 * 60 * 60 * 1000, tags: ['Went Silent', 'Post-Inquiry Drop'], summary: 'Strong initial inquiry with 3 detailed messages, then no activity after 8 days. Classic post-inquiry ghost.', properties: ['800 Riptide Ave', '63 Coconut Dr'], scoreBreakdown: { depth: 42, recency: 18, financial: 48 }, isAlerted: true, alertType: 'reengagement', alertMessage: 'Strong initial inquiry, then silence for 8 days. Re-engagement opportunity.', activity: [{ id: 1, time: '8 days ago', event: 'Last activity — viewed 800 Riptide Ave once', type: 'photos', highlight: false }, { id: 2, time: '9 days ago', event: '3rd message sent via inquiry form — asked about HOA fees', type: 'inquiry', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Tom! I pulled the HOA fee breakdown you asked about on Riptide Ave — it's actually better than I expected. Wanted to share in case that was part of what you were weighing. Still interested?" }, { channel: 'Email', subject: 'HOA info you asked about — plus a quick update', message: "Hi Tom,\n\nI wanted to follow up on the questions you had about 800 Riptide Ave — specifically the HOA fees. I got the full breakdown and it's quite reasonable.\n\nWorth a quick chat?\n\nBest,\n[Your Name]" }] },
  { id: 14, name: 'Emily Santos', initials: 'ES', phone: '(813) 555-0284', email: 'emily.santos.home@gmail.com', source: 'Facebook', temperature: 'cold', intentScore: 33, lastActive: '11 days ago', lastActiveMs: 11 * 24 * 60 * 60 * 1000, tags: ['Low Engagement', 'Early Stage'], summary: 'Browsed 3 listings casually, no saves, no financial tool engagement. Likely very early stage or just window shopping.', properties: ['Bayfront Condos Overview'], scoreBreakdown: { depth: 28, recency: 15, financial: 20 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '11 days ago', event: 'Last visit — Bayfront Condos overview page', type: 'photos', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey Emily! Just wanted to say hi — if you ever want to see what's available in your price range, I'm happy to pull a list together. No commitment needed." }, { channel: 'Email', subject: 'A few homes you might like', message: "Hi Emily,\n\nI noticed you checked out a few of our Bayfront listings recently. Happy to be a resource whenever you're ready.\n\nBest,\n[Your Name]" }] },
  { id: 15, name: 'James Fletcher', initials: 'JF', phone: '(352) 555-0951', email: 'jfletcher.re@outlook.com', source: 'Website', temperature: 'cold', intentScore: 28, lastActive: '14 days ago', lastActiveMs: 14 * 24 * 60 * 60 * 1000, tags: ['Single Visit', 'No Return'], summary: 'One visit, two listing views, no engagement. No contact form submitted. Very low intent signal — likely needs a long-term nurture approach.', properties: ['901 Marina Blvd'], scoreBreakdown: { depth: 20, recency: 10, financial: 15 }, isAlerted: false, alertType: null, alertMessage: null, activity: [{ id: 1, time: '14 days ago', event: 'Viewed 901 Marina Blvd — 5 photos then left', type: 'photos', highlight: false }], smartDrafts: [{ channel: 'Text', message: "Hey James! You browsed a few homes on our site recently. If you ever want to see what's available in your price range, I'm happy to pull a list together. No commitment needed." }, { channel: 'Email', subject: 'A few homes you might like', message: "Hi James,\n\nI noticed you checked out 901 Marina Blvd recently. There are actually a few other properties nearby that don't always show up in standard searches.\n\nHappy to help whenever you're ready.\n\nBest,\n[Your Name]" }] },
]

async function seed() {
  console.log(`\n🔥 Ignite — Seeding ${leads.length} mock leads to Firestore...\n`)

  for (const lead of leads) {
    const docId = `mock_${lead.id}`
    const createdAt = Timestamp.fromDate(new Date(Date.now() - (lead.lastActiveMs || 0)))

    await setDoc(doc(db, 'prospects', docId), {
      ...lead,
      isMockLead: true,
      status: lead.isAlerted ? 'new' : 'contacted',
      createdAt,
      lastContactAt: null,
      aiSuggestion: null,
      intent: 'buying',
      budget: 'Not specified',
      message: lead.summary,
      listingsViewed: lead.properties.map((p, i) => ({ id: `mock_prop_${lead.id}_${i}`, title: p })),
      timeOnSite: 0,
      sessionId: null,
    })

    console.log(`  ✓ ${lead.name} (score: ${lead.intentScore}, temp: ${lead.temperature})`)
  }

  console.log(`\n✅ Done! ${leads.length} leads seeded to Firestore.\n`)
  process.exit(0)
}

seed().catch(err => {
  console.error('Seed failed:', err.message)
  process.exit(1)
})
